# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user.proto", :syntax => :proto3) do
    add_message "User" do
      optional :user_id, :int32, 1
      optional :username, :string, 2
      optional :email, :string, 3
      optional :date_joined, :string, 4
      optional :is_active, :bool, 5
      optional :profile, :message, 6, "Profile"
      repeated :posts, :message, 7, "Post"
    end
    add_message "Profile" do
      optional :full_name, :string, 1
      optional :age, :int32, 2
      optional :address, :string, 3
      optional :phone_number, :string, 4
    end
    add_message "Post" do
      optional :post_id, :int32, 1
      optional :title, :string, 2
      optional :content, :string, 3
      optional :date_created, :string, 4
      optional :likes, :int32, 5
      repeated :tags, :string, 6
      repeated :comments, :message, 7, "Comment"
    end
    add_message "Comment" do
      optional :comment_id, :int32, 1
      optional :author, :string, 2
      optional :content, :string, 3
      optional :date_created, :string, 4
      optional :likes, :int32, 5
    end
  end
end

User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("User").msgclass
Profile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Profile").msgclass
Post = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Post").msgclass
Comment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Comment").msgclass
